export {
  useCheckUpdate,
  useDeleteGitApp,
  useDeleteNotificationChannel,
  useDeployUpdate,
  useExchangeGithubManifest,
  useGetAISettings,
  useGetGitApps,
  useGetNotificationSettings,
  useGetNotifications,
  useGetPublicSettings,
  useGetSettings,
  useGetSetupStatus,
  useGetUpdateStatus,
  useSaveGitApp,
  useSaveNotificationChannel,
  useTestNotification,
  useUpdateAISettings,
  useUpdateNotificationSettings,
  useUpdateSettings,
} from '#/features/settings/hooks';
