ALTER TABLE servers ADD COLUMN ssh_host TEXT DEFAULT '';
ALTER TABLE servers ADD COLUMN ssh_port INTEGER DEFAULT 22;
ALTER TABLE servers ADD COLUMN ssh_user TEXT DEFAULT 'root';
ALTER TABLE servers ADD COLUMN ssh_key TEXT DEFAULT '';
ALTER TABLE servers ADD COLUMN ssh_password TEXT DEFAULT '';
