blank_issues_enabled: false
contact_links:
  - name: Questions & Community Discussions
    url: https://github.com/buildwithtechx/codedock/discussions
    about: Ask your questions and discuss ideas with the Codedock community.
