/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAiRouteImport } from './routes/_dashboard.ai'
import { Route as DashboardApiAccessRouteImport } from './routes/_dashboard.api-access'
import { Route as DashboardAppsRouteImport } from './routes/_dashboard.apps'
import { Route as DashboardAuditLogsRouteImport } from './routes/_dashboard.audit-logs'
import { Route as DashboardBackupsRouteImport } from './routes/_dashboard.backups'
import { Route as DashboardDeploymentsRouteImport } from './routes/_dashboard.deployments'
import { Route as DashboardDnsRouteImport } from './routes/_dashboard.dns'
import { Route as DashboardMaintenanceRouteImport } from './routes/_dashboard.maintenance'
import { Route as DashboardMigrationsRouteImport } from './routes/_dashboard.migrations'
import { Route as DashboardOrganizationsRouteImport } from './routes/_dashboard.organizations'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard.projects'
import { Route as DashboardS3DestinationsRouteImport } from './routes/_dashboard.s3-destinations'
import { Route as DashboardScheduledTasksRouteImport } from './routes/_dashboard.scheduled-tasks'
import { Route as DashboardServersRouteImport } from './routes/_dashboard.servers'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardSourcesRouteImport } from './routes/_dashboard.sources'
import { Route as DashboardUpdatesRouteImport } from './routes/_dashboard.updates'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard.users'
import { Route as DashboardAppsNewRouteImport } from './routes/_dashboard.apps.new'
import { Route as DashboardOrganizationsOrganizationIdRouteImport } from './routes/_dashboard.organizations.$organizationId'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard.projects.index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/_dashboard.projects/$projectId'
import { Route as DashboardProjectsNewRouteImport } from './routes/_dashboard.projects.new'
import { Route as DashboardServersServerIdRouteImport } from './routes/_dashboard.servers.$serverId'
import { Route as DashboardServersNewRouteImport } from './routes/_dashboard.servers.new'
import { Route as DashboardServicesServiceIdRouteImport } from './routes/_dashboard.services/$serviceId'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/_dashboard.projects/$projectId.index'
import { Route as DashboardProjectsProjectIdCanvasRouteImport } from './routes/_dashboard.projects/$projectId.canvas'
import { Route as DashboardProjectsProjectIdComposeRouteImport } from './routes/_dashboard.projects/$projectId.compose'
import { Route as DashboardProjectsProjectIdNewRouteImport } from './routes/_dashboard.projects/$projectId.new'
import { Route as DashboardProjectsProjectIdScheduledTasksRouteImport } from './routes/_dashboard.projects/$projectId.scheduled-tasks'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/_dashboard.projects/$projectId.settings'
import { Route as DashboardServicesServiceIdIndexRouteImport } from './routes/_dashboard.services/$serviceId.index'
import { Route as DashboardServicesServiceIdBuildRouteImport } from './routes/_dashboard.services/$serviceId.build'
import { Route as DashboardServicesServiceIdDangerRouteImport } from './routes/_dashboard.services/$serviceId.danger'
import { Route as DashboardServicesServiceIdDeploymentsRouteImport } from './routes/_dashboard.services/$serviceId.deployments'
import { Route as DashboardServicesServiceIdDomainsRouteImport } from './routes/_dashboard.services/$serviceId.domains'
import { Route as DashboardServicesServiceIdLogDrainsRouteImport } from './routes/_dashboard.services/$serviceId.log-drains'
import { Route as DashboardServicesServiceIdMetricsRouteImport } from './routes/_dashboard.services/$serviceId.metrics'
import { Route as DashboardServicesServiceIdPreviewsRouteImport } from './routes/_dashboard.services/$serviceId.previews'
import { Route as DashboardServicesServiceIdRouteRulesRouteImport } from './routes/_dashboard.services/$serviceId.route-rules'
import { Route as DashboardServicesServiceIdScheduledTasksRouteImport } from './routes/_dashboard.services/$serviceId.scheduled-tasks'
import { Route as DashboardServicesServiceIdServerlessRouteImport } from './routes/_dashboard.services/$serviceId.serverless'
import { Route as DashboardServicesServiceIdTerminalRouteImport } from './routes/_dashboard.services/$serviceId.terminal'
import { Route as DashboardServicesServiceIdVariablesRouteImport } from './routes/_dashboard.services/$serviceId.variables'
import { Route as DashboardServicesServiceIdVolumesRouteImport } from './routes/_dashboard.services/$serviceId.volumes'
import { Route as DashboardServicesServiceIdWebhooksRouteImport } from './routes/_dashboard.services/$serviceId.webhooks'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiAccessRoute = DashboardApiAccessRouteImport.update({
  id: '/api-access',
  path: '/api-access',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackupsRoute = DashboardBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDnsRoute = DashboardDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMaintenanceRoute = DashboardMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMigrationsRoute = DashboardMigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationsRoute = DashboardOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardS3DestinationsRoute = DashboardS3DestinationsRouteImport.update({
  id: '/s3-destinations',
  path: '/s3-destinations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduledTasksRoute = DashboardScheduledTasksRouteImport.update({
  id: '/scheduled-tasks',
  path: '/scheduled-tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServersRoute = DashboardServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesRoute = DashboardSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUpdatesRoute = DashboardUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsNewRoute = DashboardAppsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const DashboardOrganizationsOrganizationIdRoute =
  DashboardOrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => DashboardOrganizationsRoute,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardServersServerIdRoute =
  DashboardServersServerIdRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => DashboardServersRoute,
  } as any)
const DashboardServersNewRoute = DashboardServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardServersRoute,
} as any)
const DashboardServicesServiceIdRoute =
  DashboardServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdCanvasRoute =
  DashboardProjectsProjectIdCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdComposeRoute =
  DashboardProjectsProjectIdComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdNewRoute =
  DashboardProjectsProjectIdNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdScheduledTasksRoute =
  DashboardProjectsProjectIdScheduledTasksRouteImport.update({
    id: '/scheduled-tasks',
    path: '/scheduled-tasks',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardServicesServiceIdIndexRoute =
  DashboardServicesServiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdBuildRoute =
  DashboardServicesServiceIdBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdDangerRoute =
  DashboardServicesServiceIdDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdDeploymentsRoute =
  DashboardServicesServiceIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdDomainsRoute =
  DashboardServicesServiceIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdLogDrainsRoute =
  DashboardServicesServiceIdLogDrainsRouteImport.update({
    id: '/log-drains',
    path: '/log-drains',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdMetricsRoute =
  DashboardServicesServiceIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdPreviewsRoute =
  DashboardServicesServiceIdPreviewsRouteImport.update({
    id: '/previews',
    path: '/previews',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdRouteRulesRoute =
  DashboardServicesServiceIdRouteRulesRouteImport.update({
    id: '/route-rules',
    path: '/route-rules',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdScheduledTasksRoute =
  DashboardServicesServiceIdScheduledTasksRouteImport.update({
    id: '/scheduled-tasks',
    path: '/scheduled-tasks',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdServerlessRoute =
  DashboardServicesServiceIdServerlessRouteImport.update({
    id: '/serverless',
    path: '/serverless',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdTerminalRoute =
  DashboardServicesServiceIdTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdVariablesRoute =
  DashboardServicesServiceIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdVolumesRoute =
  DashboardServicesServiceIdVolumesRouteImport.update({
    id: '/volumes',
    path: '/volumes',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdWebhooksRoute =
  DashboardServicesServiceIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/ai': typeof DashboardAiRoute
  '/api-access': typeof DashboardApiAccessRoute
  '/apps': typeof DashboardAppsRouteWithChildren
  '/audit-logs': typeof DashboardAuditLogsRoute
  '/backups': typeof DashboardBackupsRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/dns': typeof DashboardDnsRoute
  '/maintenance': typeof DashboardMaintenanceRoute
  '/migrations': typeof DashboardMigrationsRoute
  '/organizations': typeof DashboardOrganizationsRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/s3-destinations': typeof DashboardS3DestinationsRoute
  '/scheduled-tasks': typeof DashboardScheduledTasksRoute
  '/servers': typeof DashboardServersRouteWithChildren
  '/settings': typeof DashboardSettingsRoute
  '/sources': typeof DashboardSourcesRoute
  '/updates': typeof DashboardUpdatesRoute
  '/users': typeof DashboardUsersRoute
  '/apps/new': typeof DashboardAppsNewRoute
  '/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/projects/new': typeof DashboardProjectsNewRoute
  '/servers/$serverId': typeof DashboardServersServerIdRoute
  '/servers/new': typeof DashboardServersNewRoute
  '/services/$serviceId': typeof DashboardServicesServiceIdRouteWithChildren
  '/projects/': typeof DashboardProjectsIndexRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/new': typeof DashboardProjectsProjectIdNewRoute
  '/projects/$projectId/scheduled-tasks': typeof DashboardProjectsProjectIdScheduledTasksRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/danger': typeof DashboardServicesServiceIdDangerRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/log-drains': typeof DashboardServicesServiceIdLogDrainsRoute
  '/services/$serviceId/metrics': typeof DashboardServicesServiceIdMetricsRoute
  '/services/$serviceId/previews': typeof DashboardServicesServiceIdPreviewsRoute
  '/services/$serviceId/route-rules': typeof DashboardServicesServiceIdRouteRulesRoute
  '/services/$serviceId/scheduled-tasks': typeof DashboardServicesServiceIdScheduledTasksRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/services/$serviceId/volumes': typeof DashboardServicesServiceIdVolumesRoute
  '/services/$serviceId/webhooks': typeof DashboardServicesServiceIdWebhooksRoute
  '/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/ai': typeof DashboardAiRoute
  '/api-access': typeof DashboardApiAccessRoute
  '/apps': typeof DashboardAppsRouteWithChildren
  '/audit-logs': typeof DashboardAuditLogsRoute
  '/backups': typeof DashboardBackupsRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/dns': typeof DashboardDnsRoute
  '/maintenance': typeof DashboardMaintenanceRoute
  '/migrations': typeof DashboardMigrationsRoute
  '/organizations': typeof DashboardOrganizationsRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/s3-destinations': typeof DashboardS3DestinationsRoute
  '/scheduled-tasks': typeof DashboardScheduledTasksRoute
  '/servers': typeof DashboardServersRouteWithChildren
  '/settings': typeof DashboardSettingsRoute
  '/sources': typeof DashboardSourcesRoute
  '/updates': typeof DashboardUpdatesRoute
  '/users': typeof DashboardUsersRoute
  '/apps/new': typeof DashboardAppsNewRoute
  '/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/projects/new': typeof DashboardProjectsNewRoute
  '/servers/$serverId': typeof DashboardServersServerIdRoute
  '/servers/new': typeof DashboardServersNewRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/new': typeof DashboardProjectsProjectIdNewRoute
  '/projects/$projectId/scheduled-tasks': typeof DashboardProjectsProjectIdScheduledTasksRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/danger': typeof DashboardServicesServiceIdDangerRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/log-drains': typeof DashboardServicesServiceIdLogDrainsRoute
  '/services/$serviceId/metrics': typeof DashboardServicesServiceIdMetricsRoute
  '/services/$serviceId/previews': typeof DashboardServicesServiceIdPreviewsRoute
  '/services/$serviceId/route-rules': typeof DashboardServicesServiceIdRouteRulesRoute
  '/services/$serviceId/scheduled-tasks': typeof DashboardServicesServiceIdScheduledTasksRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/services/$serviceId/volumes': typeof DashboardServicesServiceIdVolumesRoute
  '/services/$serviceId/webhooks': typeof DashboardServicesServiceIdWebhooksRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_dashboard/ai': typeof DashboardAiRoute
  '/_dashboard/api-access': typeof DashboardApiAccessRoute
  '/_dashboard/apps': typeof DashboardAppsRouteWithChildren
  '/_dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/_dashboard/backups': typeof DashboardBackupsRoute
  '/_dashboard/deployments': typeof DashboardDeploymentsRoute
  '/_dashboard/dns': typeof DashboardDnsRoute
  '/_dashboard/maintenance': typeof DashboardMaintenanceRoute
  '/_dashboard/migrations': typeof DashboardMigrationsRoute
  '/_dashboard/organizations': typeof DashboardOrganizationsRouteWithChildren
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/_dashboard/s3-destinations': typeof DashboardS3DestinationsRoute
  '/_dashboard/scheduled-tasks': typeof DashboardScheduledTasksRoute
  '/_dashboard/servers': typeof DashboardServersRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/sources': typeof DashboardSourcesRoute
  '/_dashboard/updates': typeof DashboardUpdatesRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/apps/new': typeof DashboardAppsNewRoute
  '/_dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/_dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/_dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/_dashboard/servers/$serverId': typeof DashboardServersServerIdRoute
  '/_dashboard/servers/new': typeof DashboardServersNewRoute
  '/_dashboard/services/$serviceId': typeof DashboardServicesServiceIdRouteWithChildren
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/_dashboard/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/_dashboard/projects/$projectId/new': typeof DashboardProjectsProjectIdNewRoute
  '/_dashboard/projects/$projectId/scheduled-tasks': typeof DashboardProjectsProjectIdScheduledTasksRoute
  '/_dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/_dashboard/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/_dashboard/services/$serviceId/danger': typeof DashboardServicesServiceIdDangerRoute
  '/_dashboard/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/_dashboard/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/_dashboard/services/$serviceId/log-drains': typeof DashboardServicesServiceIdLogDrainsRoute
  '/_dashboard/services/$serviceId/metrics': typeof DashboardServicesServiceIdMetricsRoute
  '/_dashboard/services/$serviceId/previews': typeof DashboardServicesServiceIdPreviewsRoute
  '/_dashboard/services/$serviceId/route-rules': typeof DashboardServicesServiceIdRouteRulesRoute
  '/_dashboard/services/$serviceId/scheduled-tasks': typeof DashboardServicesServiceIdScheduledTasksRoute
  '/_dashboard/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/_dashboard/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/_dashboard/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/_dashboard/services/$serviceId/volumes': typeof DashboardServicesServiceIdVolumesRoute
  '/_dashboard/services/$serviceId/webhooks': typeof DashboardServicesServiceIdWebhooksRoute
  '/_dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/_dashboard/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/ai'
    | '/api-access'
    | '/apps'
    | '/audit-logs'
    | '/backups'
    | '/deployments'
    | '/dns'
    | '/maintenance'
    | '/migrations'
    | '/organizations'
    | '/profile'
    | '/projects'
    | '/s3-destinations'
    | '/scheduled-tasks'
    | '/servers'
    | '/settings'
    | '/sources'
    | '/updates'
    | '/users'
    | '/apps/new'
    | '/organizations/$organizationId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/services/$serviceId'
    | '/projects/'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/new'
    | '/projects/$projectId/scheduled-tasks'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/danger'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/log-drains'
    | '/services/$serviceId/metrics'
    | '/services/$serviceId/previews'
    | '/services/$serviceId/route-rules'
    | '/services/$serviceId/scheduled-tasks'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/services/$serviceId/volumes'
    | '/services/$serviceId/webhooks'
    | '/projects/$projectId/'
    | '/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/ai'
    | '/api-access'
    | '/apps'
    | '/audit-logs'
    | '/backups'
    | '/deployments'
    | '/dns'
    | '/maintenance'
    | '/migrations'
    | '/organizations'
    | '/profile'
    | '/s3-destinations'
    | '/scheduled-tasks'
    | '/servers'
    | '/settings'
    | '/sources'
    | '/updates'
    | '/users'
    | '/apps/new'
    | '/organizations/$organizationId'
    | '/projects/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/projects'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/new'
    | '/projects/$projectId/scheduled-tasks'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/danger'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/log-drains'
    | '/services/$serviceId/metrics'
    | '/services/$serviceId/previews'
    | '/services/$serviceId/route-rules'
    | '/services/$serviceId/scheduled-tasks'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/services/$serviceId/volumes'
    | '/services/$serviceId/webhooks'
    | '/projects/$projectId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_dashboard/ai'
    | '/_dashboard/api-access'
    | '/_dashboard/apps'
    | '/_dashboard/audit-logs'
    | '/_dashboard/backups'
    | '/_dashboard/deployments'
    | '/_dashboard/dns'
    | '/_dashboard/maintenance'
    | '/_dashboard/migrations'
    | '/_dashboard/organizations'
    | '/_dashboard/profile'
    | '/_dashboard/projects'
    | '/_dashboard/s3-destinations'
    | '/_dashboard/scheduled-tasks'
    | '/_dashboard/servers'
    | '/_dashboard/settings'
    | '/_dashboard/sources'
    | '/_dashboard/updates'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/apps/new'
    | '/_dashboard/organizations/$organizationId'
    | '/_dashboard/projects/$projectId'
    | '/_dashboard/projects/new'
    | '/_dashboard/servers/$serverId'
    | '/_dashboard/servers/new'
    | '/_dashboard/services/$serviceId'
    | '/_dashboard/projects/'
    | '/_dashboard/projects/$projectId/canvas'
    | '/_dashboard/projects/$projectId/compose'
    | '/_dashboard/projects/$projectId/new'
    | '/_dashboard/projects/$projectId/scheduled-tasks'
    | '/_dashboard/projects/$projectId/settings'
    | '/_dashboard/services/$serviceId/build'
    | '/_dashboard/services/$serviceId/danger'
    | '/_dashboard/services/$serviceId/deployments'
    | '/_dashboard/services/$serviceId/domains'
    | '/_dashboard/services/$serviceId/log-drains'
    | '/_dashboard/services/$serviceId/metrics'
    | '/_dashboard/services/$serviceId/previews'
    | '/_dashboard/services/$serviceId/route-rules'
    | '/_dashboard/services/$serviceId/scheduled-tasks'
    | '/_dashboard/services/$serviceId/serverless'
    | '/_dashboard/services/$serviceId/terminal'
    | '/_dashboard/services/$serviceId/variables'
    | '/_dashboard/services/$serviceId/volumes'
    | '/_dashboard/services/$serviceId/webhooks'
    | '/_dashboard/projects/$projectId/'
    | '/_dashboard/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ai': {
      id: '/_dashboard/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/api-access': {
      id: '/_dashboard/api-access'
      path: '/api-access'
      fullPath: '/api-access'
      preLoaderRoute: typeof DashboardApiAccessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps': {
      id: '/_dashboard/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit-logs': {
      id: '/_dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/backups': {
      id: '/_dashboard/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof DashboardBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deployments': {
      id: '/_dashboard/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dns': {
      id: '/_dashboard/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DashboardDnsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/maintenance': {
      id: '/_dashboard/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof DashboardMaintenanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/migrations': {
      id: '/_dashboard/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof DashboardMigrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organizations': {
      id: '/_dashboard/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/s3-destinations': {
      id: '/_dashboard/s3-destinations'
      path: '/s3-destinations'
      fullPath: '/s3-destinations'
      preLoaderRoute: typeof DashboardS3DestinationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/scheduled-tasks': {
      id: '/_dashboard/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/scheduled-tasks'
      preLoaderRoute: typeof DashboardScheduledTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/servers': {
      id: '/_dashboard/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof DashboardServersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sources': {
      id: '/_dashboard/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof DashboardSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/updates': {
      id: '/_dashboard/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof DashboardUpdatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps/new': {
      id: '/_dashboard/apps/new'
      path: '/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof DashboardAppsNewRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/_dashboard/organizations/$organizationId': {
      id: '/_dashboard/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
      parentRoute: typeof DashboardOrganizationsRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId': {
      id: '/_dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/new': {
      id: '/_dashboard/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/servers/$serverId': {
      id: '/_dashboard/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof DashboardServersServerIdRouteImport
      parentRoute: typeof DashboardServersRoute
    }
    '/_dashboard/servers/new': {
      id: '/_dashboard/servers/new'
      path: '/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof DashboardServersNewRouteImport
      parentRoute: typeof DashboardServersRoute
    }
    '/_dashboard/services/$serviceId': {
      id: '/_dashboard/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof DashboardServicesServiceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$projectId/': {
      id: '/_dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/canvas': {
      id: '/_dashboard/projects/$projectId/canvas'
      path: '/canvas'
      fullPath: '/projects/$projectId/canvas'
      preLoaderRoute: typeof DashboardProjectsProjectIdCanvasRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/compose': {
      id: '/_dashboard/projects/$projectId/compose'
      path: '/compose'
      fullPath: '/projects/$projectId/compose'
      preLoaderRoute: typeof DashboardProjectsProjectIdComposeRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/new': {
      id: '/_dashboard/projects/$projectId/new'
      path: '/new'
      fullPath: '/projects/$projectId/new'
      preLoaderRoute: typeof DashboardProjectsProjectIdNewRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/scheduled-tasks': {
      id: '/_dashboard/projects/$projectId/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/projects/$projectId/scheduled-tasks'
      preLoaderRoute: typeof DashboardProjectsProjectIdScheduledTasksRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/settings': {
      id: '/_dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/services/$serviceId/': {
      id: '/_dashboard/services/$serviceId/'
      path: '/'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof DashboardServicesServiceIdIndexRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/build': {
      id: '/_dashboard/services/$serviceId/build'
      path: '/build'
      fullPath: '/services/$serviceId/build'
      preLoaderRoute: typeof DashboardServicesServiceIdBuildRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/danger': {
      id: '/_dashboard/services/$serviceId/danger'
      path: '/danger'
      fullPath: '/services/$serviceId/danger'
      preLoaderRoute: typeof DashboardServicesServiceIdDangerRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/deployments': {
      id: '/_dashboard/services/$serviceId/deployments'
      path: '/deployments'
      fullPath: '/services/$serviceId/deployments'
      preLoaderRoute: typeof DashboardServicesServiceIdDeploymentsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/domains': {
      id: '/_dashboard/services/$serviceId/domains'
      path: '/domains'
      fullPath: '/services/$serviceId/domains'
      preLoaderRoute: typeof DashboardServicesServiceIdDomainsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/log-drains': {
      id: '/_dashboard/services/$serviceId/log-drains'
      path: '/log-drains'
      fullPath: '/services/$serviceId/log-drains'
      preLoaderRoute: typeof DashboardServicesServiceIdLogDrainsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/metrics': {
      id: '/_dashboard/services/$serviceId/metrics'
      path: '/metrics'
      fullPath: '/services/$serviceId/metrics'
      preLoaderRoute: typeof DashboardServicesServiceIdMetricsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/previews': {
      id: '/_dashboard/services/$serviceId/previews'
      path: '/previews'
      fullPath: '/services/$serviceId/previews'
      preLoaderRoute: typeof DashboardServicesServiceIdPreviewsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/route-rules': {
      id: '/_dashboard/services/$serviceId/route-rules'
      path: '/route-rules'
      fullPath: '/services/$serviceId/route-rules'
      preLoaderRoute: typeof DashboardServicesServiceIdRouteRulesRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/scheduled-tasks': {
      id: '/_dashboard/services/$serviceId/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/services/$serviceId/scheduled-tasks'
      preLoaderRoute: typeof DashboardServicesServiceIdScheduledTasksRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/serverless': {
      id: '/_dashboard/services/$serviceId/serverless'
      path: '/serverless'
      fullPath: '/services/$serviceId/serverless'
      preLoaderRoute: typeof DashboardServicesServiceIdServerlessRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/terminal': {
      id: '/_dashboard/services/$serviceId/terminal'
      path: '/terminal'
      fullPath: '/services/$serviceId/terminal'
      preLoaderRoute: typeof DashboardServicesServiceIdTerminalRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/variables': {
      id: '/_dashboard/services/$serviceId/variables'
      path: '/variables'
      fullPath: '/services/$serviceId/variables'
      preLoaderRoute: typeof DashboardServicesServiceIdVariablesRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/volumes': {
      id: '/_dashboard/services/$serviceId/volumes'
      path: '/volumes'
      fullPath: '/services/$serviceId/volumes'
      preLoaderRoute: typeof DashboardServicesServiceIdVolumesRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/webhooks': {
      id: '/_dashboard/services/$serviceId/webhooks'
      path: '/webhooks'
      fullPath: '/services/$serviceId/webhooks'
      preLoaderRoute: typeof DashboardServicesServiceIdWebhooksRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardAppsRouteChildren {
  DashboardAppsNewRoute: typeof DashboardAppsNewRoute
}

const DashboardAppsRouteChildren: DashboardAppsRouteChildren = {
  DashboardAppsNewRoute: DashboardAppsNewRoute,
}

const DashboardAppsRouteWithChildren = DashboardAppsRoute._addFileChildren(
  DashboardAppsRouteChildren,
)

interface DashboardOrganizationsRouteChildren {
  DashboardOrganizationsOrganizationIdRoute: typeof DashboardOrganizationsOrganizationIdRoute
}

const DashboardOrganizationsRouteChildren: DashboardOrganizationsRouteChildren =
  {
    DashboardOrganizationsOrganizationIdRoute:
      DashboardOrganizationsOrganizationIdRoute,
  }

const DashboardOrganizationsRouteWithChildren =
  DashboardOrganizationsRoute._addFileChildren(
    DashboardOrganizationsRouteChildren,
  )

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdCanvasRoute: typeof DashboardProjectsProjectIdCanvasRoute
  DashboardProjectsProjectIdComposeRoute: typeof DashboardProjectsProjectIdComposeRoute
  DashboardProjectsProjectIdNewRoute: typeof DashboardProjectsProjectIdNewRoute
  DashboardProjectsProjectIdScheduledTasksRoute: typeof DashboardProjectsProjectIdScheduledTasksRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdCanvasRoute:
      DashboardProjectsProjectIdCanvasRoute,
    DashboardProjectsProjectIdComposeRoute:
      DashboardProjectsProjectIdComposeRoute,
    DashboardProjectsProjectIdNewRoute: DashboardProjectsProjectIdNewRoute,
    DashboardProjectsProjectIdScheduledTasksRoute:
      DashboardProjectsProjectIdScheduledTasksRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardServersRouteChildren {
  DashboardServersServerIdRoute: typeof DashboardServersServerIdRoute
  DashboardServersNewRoute: typeof DashboardServersNewRoute
}

const DashboardServersRouteChildren: DashboardServersRouteChildren = {
  DashboardServersServerIdRoute: DashboardServersServerIdRoute,
  DashboardServersNewRoute: DashboardServersNewRoute,
}

const DashboardServersRouteWithChildren =
  DashboardServersRoute._addFileChildren(DashboardServersRouteChildren)

interface DashboardServicesServiceIdRouteChildren {
  DashboardServicesServiceIdBuildRoute: typeof DashboardServicesServiceIdBuildRoute
  DashboardServicesServiceIdDangerRoute: typeof DashboardServicesServiceIdDangerRoute
  DashboardServicesServiceIdDeploymentsRoute: typeof DashboardServicesServiceIdDeploymentsRoute
  DashboardServicesServiceIdDomainsRoute: typeof DashboardServicesServiceIdDomainsRoute
  DashboardServicesServiceIdLogDrainsRoute: typeof DashboardServicesServiceIdLogDrainsRoute
  DashboardServicesServiceIdMetricsRoute: typeof DashboardServicesServiceIdMetricsRoute
  DashboardServicesServiceIdPreviewsRoute: typeof DashboardServicesServiceIdPreviewsRoute
  DashboardServicesServiceIdRouteRulesRoute: typeof DashboardServicesServiceIdRouteRulesRoute
  DashboardServicesServiceIdScheduledTasksRoute: typeof DashboardServicesServiceIdScheduledTasksRoute
  DashboardServicesServiceIdServerlessRoute: typeof DashboardServicesServiceIdServerlessRoute
  DashboardServicesServiceIdTerminalRoute: typeof DashboardServicesServiceIdTerminalRoute
  DashboardServicesServiceIdVariablesRoute: typeof DashboardServicesServiceIdVariablesRoute
  DashboardServicesServiceIdVolumesRoute: typeof DashboardServicesServiceIdVolumesRoute
  DashboardServicesServiceIdWebhooksRoute: typeof DashboardServicesServiceIdWebhooksRoute
  DashboardServicesServiceIdIndexRoute: typeof DashboardServicesServiceIdIndexRoute
}

const DashboardServicesServiceIdRouteChildren: DashboardServicesServiceIdRouteChildren =
  {
    DashboardServicesServiceIdBuildRoute: DashboardServicesServiceIdBuildRoute,
    DashboardServicesServiceIdDangerRoute:
      DashboardServicesServiceIdDangerRoute,
    DashboardServicesServiceIdDeploymentsRoute:
      DashboardServicesServiceIdDeploymentsRoute,
    DashboardServicesServiceIdDomainsRoute:
      DashboardServicesServiceIdDomainsRoute,
    DashboardServicesServiceIdLogDrainsRoute:
      DashboardServicesServiceIdLogDrainsRoute,
    DashboardServicesServiceIdMetricsRoute:
      DashboardServicesServiceIdMetricsRoute,
    DashboardServicesServiceIdPreviewsRoute:
      DashboardServicesServiceIdPreviewsRoute,
    DashboardServicesServiceIdRouteRulesRoute:
      DashboardServicesServiceIdRouteRulesRoute,
    DashboardServicesServiceIdScheduledTasksRoute:
      DashboardServicesServiceIdScheduledTasksRoute,
    DashboardServicesServiceIdServerlessRoute:
      DashboardServicesServiceIdServerlessRoute,
    DashboardServicesServiceIdTerminalRoute:
      DashboardServicesServiceIdTerminalRoute,
    DashboardServicesServiceIdVariablesRoute:
      DashboardServicesServiceIdVariablesRoute,
    DashboardServicesServiceIdVolumesRoute:
      DashboardServicesServiceIdVolumesRoute,
    DashboardServicesServiceIdWebhooksRoute:
      DashboardServicesServiceIdWebhooksRoute,
    DashboardServicesServiceIdIndexRoute: DashboardServicesServiceIdIndexRoute,
  }

const DashboardServicesServiceIdRouteWithChildren =
  DashboardServicesServiceIdRoute._addFileChildren(
    DashboardServicesServiceIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardApiAccessRoute: typeof DashboardApiAccessRoute
  DashboardAppsRoute: typeof DashboardAppsRouteWithChildren
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardBackupsRoute: typeof DashboardBackupsRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardDnsRoute: typeof DashboardDnsRoute
  DashboardMaintenanceRoute: typeof DashboardMaintenanceRoute
  DashboardMigrationsRoute: typeof DashboardMigrationsRoute
  DashboardOrganizationsRoute: typeof DashboardOrganizationsRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardS3DestinationsRoute: typeof DashboardS3DestinationsRoute
  DashboardScheduledTasksRoute: typeof DashboardScheduledTasksRoute
  DashboardServersRoute: typeof DashboardServersRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSourcesRoute: typeof DashboardSourcesRoute
  DashboardUpdatesRoute: typeof DashboardUpdatesRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardServicesServiceIdRoute: typeof DashboardServicesServiceIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardApiAccessRoute: DashboardApiAccessRoute,
  DashboardAppsRoute: DashboardAppsRouteWithChildren,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardBackupsRoute: DashboardBackupsRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardDnsRoute: DashboardDnsRoute,
  DashboardMaintenanceRoute: DashboardMaintenanceRoute,
  DashboardMigrationsRoute: DashboardMigrationsRoute,
  DashboardOrganizationsRoute: DashboardOrganizationsRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardS3DestinationsRoute: DashboardS3DestinationsRoute,
  DashboardScheduledTasksRoute: DashboardScheduledTasksRoute,
  DashboardServersRoute: DashboardServersRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSourcesRoute: DashboardSourcesRoute,
  DashboardUpdatesRoute: DashboardUpdatesRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardServicesServiceIdRoute: DashboardServicesServiceIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
