/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth.verify-email'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAppsRouteImport } from './routes/_dashboard.apps'
import { Route as DashboardAuditRouteImport } from './routes/_dashboard.audit'
import { Route as DashboardBackupsRouteImport } from './routes/_dashboard.backups'
import { Route as DashboardBillingRouteImport } from './routes/_dashboard.billing'
import { Route as DashboardDeployRouteImport } from './routes/_dashboard.deploy'
import { Route as DashboardDeploymentsRouteImport } from './routes/_dashboard.deployments'
import { Route as DashboardDnsRouteImport } from './routes/_dashboard.dns'
import { Route as DashboardDomainsRouteImport } from './routes/_dashboard.domains'
import { Route as DashboardJobsRouteImport } from './routes/_dashboard.jobs'
import { Route as DashboardLibraryRouteImport } from './routes/_dashboard.library'
import { Route as DashboardMonitoringRouteImport } from './routes/_dashboard.monitoring'
import { Route as DashboardOrganizationsRouteImport } from './routes/_dashboard.organizations'
import { Route as DashboardProfileRouteImport } from './routes/_dashboard.profile'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard.projects'
import { Route as DashboardServersRouteImport } from './routes/_dashboard.servers'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardAppsIndexRouteImport } from './routes/_dashboard.apps.index'
import { Route as DashboardAppsNewRouteImport } from './routes/_dashboard.apps.new'
import { Route as DashboardBackupsIndexRouteImport } from './routes/_dashboard.backups.index'
import { Route as DashboardBackupsBackupIdRouteImport } from './routes/_dashboard.backups.$backupId'
import { Route as DashboardDeployIndexRouteImport } from './routes/_dashboard.deploy.index'
import { Route as DashboardDeploySlugRouteImport } from './routes/_dashboard.deploy.$slug'
import { Route as DashboardDeploymentsIndexRouteImport } from './routes/_dashboard.deployments.index'
import { Route as DashboardDeploymentsDeploymentIdRouteImport } from './routes/_dashboard.deployments.$deploymentId'
import { Route as DashboardJobsIndexRouteImport } from './routes/_dashboard.jobs.index'
import { Route as DashboardJobsJobIdRouteImport } from './routes/_dashboard.jobs.$jobId'
import { Route as DashboardJobsNewRouteImport } from './routes/_dashboard.jobs.new'
import { Route as DashboardOrganizationsIndexRouteImport } from './routes/_dashboard.organizations.index'
import { Route as DashboardOrganizationsOrganizationIdRouteImport } from './routes/_dashboard.organizations.$organizationId'
import { Route as DashboardProjectsIndexRouteImport } from './routes/_dashboard.projects.index'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/_dashboard.projects/$projectId'
import { Route as DashboardProjectsNewRouteImport } from './routes/_dashboard.projects.new'
import { Route as DashboardServersIndexRouteImport } from './routes/_dashboard.servers.index'
import { Route as DashboardServersServerIdRouteImport } from './routes/_dashboard.servers.$serverId'
import { Route as DashboardServersNewRouteImport } from './routes/_dashboard.servers.new'
import { Route as DashboardServicesServiceIdRouteImport } from './routes/_dashboard.services/$serviceId'
import { Route as DashboardAppsNewIndexRouteImport } from './routes/_dashboard.apps.new.index'
import { Route as DashboardAppsNewAppIdRouteImport } from './routes/_dashboard.apps.new.$appId'
import { Route as DashboardJobsJobIdIndexRouteImport } from './routes/_dashboard.jobs.$jobId.index'
import { Route as DashboardJobsJobIdEditRouteImport } from './routes/_dashboard.jobs.$jobId.edit'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/_dashboard.projects/$projectId.index'
import { Route as DashboardProjectsProjectIdCanvasRouteImport } from './routes/_dashboard.projects/$projectId.canvas'
import { Route as DashboardProjectsProjectIdComposeRouteImport } from './routes/_dashboard.projects/$projectId.compose'
import { Route as DashboardProjectsProjectIdDomainsRouteImport } from './routes/_dashboard.projects.$projectId.domains'
import { Route as DashboardProjectsProjectIdNewRouteImport } from './routes/_dashboard.projects/$projectId.new'
import { Route as DashboardProjectsProjectIdScheduledTasksRouteImport } from './routes/_dashboard.projects/$projectId.scheduled-tasks'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/_dashboard.projects/$projectId.settings'
import { Route as DashboardServicesServiceIdIndexRouteImport } from './routes/_dashboard.services/$serviceId.index'
import { Route as DashboardServicesServiceIdBuildRouteImport } from './routes/_dashboard.services/$serviceId.build'
import { Route as DashboardServicesServiceIdDangerRouteImport } from './routes/_dashboard.services/$serviceId.danger'
import { Route as DashboardServicesServiceIdDeploymentsRouteImport } from './routes/_dashboard.services/$serviceId.deployments'
import { Route as DashboardServicesServiceIdDomainsRouteImport } from './routes/_dashboard.services/$serviceId.domains'
import { Route as DashboardServicesServiceIdLogDrainsRouteImport } from './routes/_dashboard.services/$serviceId.log-drains'
import { Route as DashboardServicesServiceIdMetricsRouteImport } from './routes/_dashboard.services/$serviceId.metrics'
import { Route as DashboardServicesServiceIdPreviewsRouteImport } from './routes/_dashboard.services/$serviceId.previews'
import { Route as DashboardServicesServiceIdRouteRulesRouteImport } from './routes/_dashboard.services/$serviceId.route-rules'
import { Route as DashboardServicesServiceIdScheduledTasksRouteImport } from './routes/_dashboard.services/$serviceId.scheduled-tasks'
import { Route as DashboardServicesServiceIdServerlessRouteImport } from './routes/_dashboard.services/$serviceId.serverless'
import { Route as DashboardServicesServiceIdTerminalRouteImport } from './routes/_dashboard.services/$serviceId.terminal'
import { Route as DashboardServicesServiceIdVariablesRouteImport } from './routes/_dashboard.services/$serviceId.variables'
import { Route as DashboardServicesServiceIdVolumesRouteImport } from './routes/_dashboard.services/$serviceId.volumes'
import { Route as DashboardServicesServiceIdWebhooksRouteImport } from './routes/_dashboard.services/$serviceId.webhooks'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsRoute = DashboardAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBackupsRoute = DashboardBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeployRoute = DashboardDeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDnsRoute = DashboardDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMonitoringRoute = DashboardMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrganizationsRoute = DashboardOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardServersRoute = DashboardServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppsIndexRoute = DashboardAppsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const DashboardAppsNewRoute = DashboardAppsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardAppsRoute,
} as any)
const DashboardBackupsIndexRoute = DashboardBackupsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBackupsRoute,
} as any)
const DashboardBackupsBackupIdRoute =
  DashboardBackupsBackupIdRouteImport.update({
    id: '/$backupId',
    path: '/$backupId',
    getParentRoute: () => DashboardBackupsRoute,
  } as any)
const DashboardDeployIndexRoute = DashboardDeployIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardDeployRoute,
} as any)
const DashboardDeploySlugRoute = DashboardDeploySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DashboardDeployRoute,
} as any)
const DashboardDeploymentsIndexRoute =
  DashboardDeploymentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDeploymentsRoute,
  } as any)
const DashboardDeploymentsDeploymentIdRoute =
  DashboardDeploymentsDeploymentIdRouteImport.update({
    id: '/$deploymentId',
    path: '/$deploymentId',
    getParentRoute: () => DashboardDeploymentsRoute,
  } as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJobsRoute,
} as any)
const DashboardJobsJobIdRoute = DashboardJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => DashboardJobsRoute,
} as any)
const DashboardJobsNewRoute = DashboardJobsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardJobsRoute,
} as any)
const DashboardOrganizationsIndexRoute =
  DashboardOrganizationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardOrganizationsRoute,
  } as any)
const DashboardOrganizationsOrganizationIdRoute =
  DashboardOrganizationsOrganizationIdRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => DashboardOrganizationsRoute,
  } as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardServersIndexRoute = DashboardServersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardServersRoute,
} as any)
const DashboardServersServerIdRoute =
  DashboardServersServerIdRouteImport.update({
    id: '/$serverId',
    path: '/$serverId',
    getParentRoute: () => DashboardServersRoute,
  } as any)
const DashboardServersNewRoute = DashboardServersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardServersRoute,
} as any)
const DashboardServicesServiceIdRoute =
  DashboardServicesServiceIdRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAppsNewIndexRoute = DashboardAppsNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAppsNewRoute,
} as any)
const DashboardAppsNewAppIdRoute = DashboardAppsNewAppIdRouteImport.update({
  id: '/$appId',
  path: '/$appId',
  getParentRoute: () => DashboardAppsNewRoute,
} as any)
const DashboardJobsJobIdIndexRoute = DashboardJobsJobIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardJobsJobIdRoute,
} as any)
const DashboardJobsJobIdEditRoute = DashboardJobsJobIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardJobsJobIdRoute,
} as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdCanvasRoute =
  DashboardProjectsProjectIdCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdComposeRoute =
  DashboardProjectsProjectIdComposeRouteImport.update({
    id: '/compose',
    path: '/compose',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdDomainsRoute =
  DashboardProjectsProjectIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdNewRoute =
  DashboardProjectsProjectIdNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdScheduledTasksRoute =
  DashboardProjectsProjectIdScheduledTasksRouteImport.update({
    id: '/scheduled-tasks',
    path: '/scheduled-tasks',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProjectsProjectIdRoute,
  } as any)
const DashboardServicesServiceIdIndexRoute =
  DashboardServicesServiceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdBuildRoute =
  DashboardServicesServiceIdBuildRouteImport.update({
    id: '/build',
    path: '/build',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdDangerRoute =
  DashboardServicesServiceIdDangerRouteImport.update({
    id: '/danger',
    path: '/danger',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdDeploymentsRoute =
  DashboardServicesServiceIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdDomainsRoute =
  DashboardServicesServiceIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdLogDrainsRoute =
  DashboardServicesServiceIdLogDrainsRouteImport.update({
    id: '/log-drains',
    path: '/log-drains',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdMetricsRoute =
  DashboardServicesServiceIdMetricsRouteImport.update({
    id: '/metrics',
    path: '/metrics',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdPreviewsRoute =
  DashboardServicesServiceIdPreviewsRouteImport.update({
    id: '/previews',
    path: '/previews',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdRouteRulesRoute =
  DashboardServicesServiceIdRouteRulesRouteImport.update({
    id: '/route-rules',
    path: '/route-rules',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdScheduledTasksRoute =
  DashboardServicesServiceIdScheduledTasksRouteImport.update({
    id: '/scheduled-tasks',
    path: '/scheduled-tasks',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdServerlessRoute =
  DashboardServicesServiceIdServerlessRouteImport.update({
    id: '/serverless',
    path: '/serverless',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdTerminalRoute =
  DashboardServicesServiceIdTerminalRouteImport.update({
    id: '/terminal',
    path: '/terminal',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdVariablesRoute =
  DashboardServicesServiceIdVariablesRouteImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdVolumesRoute =
  DashboardServicesServiceIdVolumesRouteImport.update({
    id: '/volumes',
    path: '/volumes',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)
const DashboardServicesServiceIdWebhooksRoute =
  DashboardServicesServiceIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => DashboardServicesServiceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/apps': typeof DashboardAppsRouteWithChildren
  '/audit': typeof DashboardAuditRoute
  '/backups': typeof DashboardBackupsRouteWithChildren
  '/billing': typeof DashboardBillingRoute
  '/deploy': typeof DashboardDeployRouteWithChildren
  '/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/dns': typeof DashboardDnsRoute
  '/domains': typeof DashboardDomainsRoute
  '/jobs': typeof DashboardJobsRouteWithChildren
  '/library': typeof DashboardLibraryRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/organizations': typeof DashboardOrganizationsRouteWithChildren
  '/profile': typeof DashboardProfileRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/servers': typeof DashboardServersRouteWithChildren
  '/settings': typeof DashboardSettingsRoute
  '/apps/new': typeof DashboardAppsNewRouteWithChildren
  '/backups/$backupId': typeof DashboardBackupsBackupIdRoute
  '/deploy/$slug': typeof DashboardDeploySlugRoute
  '/deployments/$deploymentId': typeof DashboardDeploymentsDeploymentIdRoute
  '/jobs/$jobId': typeof DashboardJobsJobIdRouteWithChildren
  '/jobs/new': typeof DashboardJobsNewRoute
  '/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/projects/new': typeof DashboardProjectsNewRoute
  '/servers/$serverId': typeof DashboardServersServerIdRoute
  '/servers/new': typeof DashboardServersNewRoute
  '/services/$serviceId': typeof DashboardServicesServiceIdRouteWithChildren
  '/apps/': typeof DashboardAppsIndexRoute
  '/backups/': typeof DashboardBackupsIndexRoute
  '/deploy/': typeof DashboardDeployIndexRoute
  '/deployments/': typeof DashboardDeploymentsIndexRoute
  '/jobs/': typeof DashboardJobsIndexRoute
  '/organizations/': typeof DashboardOrganizationsIndexRoute
  '/projects/': typeof DashboardProjectsIndexRoute
  '/servers/': typeof DashboardServersIndexRoute
  '/apps/new/$appId': typeof DashboardAppsNewAppIdRoute
  '/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/domains': typeof DashboardProjectsProjectIdDomainsRoute
  '/projects/$projectId/new': typeof DashboardProjectsProjectIdNewRoute
  '/projects/$projectId/scheduled-tasks': typeof DashboardProjectsProjectIdScheduledTasksRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/danger': typeof DashboardServicesServiceIdDangerRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/log-drains': typeof DashboardServicesServiceIdLogDrainsRoute
  '/services/$serviceId/metrics': typeof DashboardServicesServiceIdMetricsRoute
  '/services/$serviceId/previews': typeof DashboardServicesServiceIdPreviewsRoute
  '/services/$serviceId/route-rules': typeof DashboardServicesServiceIdRouteRulesRoute
  '/services/$serviceId/scheduled-tasks': typeof DashboardServicesServiceIdScheduledTasksRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/services/$serviceId/volumes': typeof DashboardServicesServiceIdVolumesRoute
  '/services/$serviceId/webhooks': typeof DashboardServicesServiceIdWebhooksRoute
  '/apps/new/': typeof DashboardAppsNewIndexRoute
  '/jobs/$jobId/': typeof DashboardJobsJobIdIndexRoute
  '/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/audit': typeof DashboardAuditRoute
  '/billing': typeof DashboardBillingRoute
  '/dns': typeof DashboardDnsRoute
  '/domains': typeof DashboardDomainsRoute
  '/library': typeof DashboardLibraryRoute
  '/monitoring': typeof DashboardMonitoringRoute
  '/profile': typeof DashboardProfileRoute
  '/settings': typeof DashboardSettingsRoute
  '/backups/$backupId': typeof DashboardBackupsBackupIdRoute
  '/deploy/$slug': typeof DashboardDeploySlugRoute
  '/deployments/$deploymentId': typeof DashboardDeploymentsDeploymentIdRoute
  '/jobs/new': typeof DashboardJobsNewRoute
  '/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/projects/new': typeof DashboardProjectsNewRoute
  '/servers/$serverId': typeof DashboardServersServerIdRoute
  '/servers/new': typeof DashboardServersNewRoute
  '/apps': typeof DashboardAppsIndexRoute
  '/backups': typeof DashboardBackupsIndexRoute
  '/deploy': typeof DashboardDeployIndexRoute
  '/deployments': typeof DashboardDeploymentsIndexRoute
  '/jobs': typeof DashboardJobsIndexRoute
  '/organizations': typeof DashboardOrganizationsIndexRoute
  '/projects': typeof DashboardProjectsIndexRoute
  '/servers': typeof DashboardServersIndexRoute
  '/apps/new/$appId': typeof DashboardAppsNewAppIdRoute
  '/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/domains': typeof DashboardProjectsProjectIdDomainsRoute
  '/projects/$projectId/new': typeof DashboardProjectsProjectIdNewRoute
  '/projects/$projectId/scheduled-tasks': typeof DashboardProjectsProjectIdScheduledTasksRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/danger': typeof DashboardServicesServiceIdDangerRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/log-drains': typeof DashboardServicesServiceIdLogDrainsRoute
  '/services/$serviceId/metrics': typeof DashboardServicesServiceIdMetricsRoute
  '/services/$serviceId/previews': typeof DashboardServicesServiceIdPreviewsRoute
  '/services/$serviceId/route-rules': typeof DashboardServicesServiceIdRouteRulesRoute
  '/services/$serviceId/scheduled-tasks': typeof DashboardServicesServiceIdScheduledTasksRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/services/$serviceId/volumes': typeof DashboardServicesServiceIdVolumesRoute
  '/services/$serviceId/webhooks': typeof DashboardServicesServiceIdWebhooksRoute
  '/apps/new': typeof DashboardAppsNewIndexRoute
  '/jobs/$jobId': typeof DashboardJobsJobIdIndexRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_dashboard/apps': typeof DashboardAppsRouteWithChildren
  '/_dashboard/audit': typeof DashboardAuditRoute
  '/_dashboard/backups': typeof DashboardBackupsRouteWithChildren
  '/_dashboard/billing': typeof DashboardBillingRoute
  '/_dashboard/deploy': typeof DashboardDeployRouteWithChildren
  '/_dashboard/deployments': typeof DashboardDeploymentsRouteWithChildren
  '/_dashboard/dns': typeof DashboardDnsRoute
  '/_dashboard/domains': typeof DashboardDomainsRoute
  '/_dashboard/jobs': typeof DashboardJobsRouteWithChildren
  '/_dashboard/library': typeof DashboardLibraryRoute
  '/_dashboard/monitoring': typeof DashboardMonitoringRoute
  '/_dashboard/organizations': typeof DashboardOrganizationsRouteWithChildren
  '/_dashboard/profile': typeof DashboardProfileRoute
  '/_dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/_dashboard/servers': typeof DashboardServersRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/apps/new': typeof DashboardAppsNewRouteWithChildren
  '/_dashboard/backups/$backupId': typeof DashboardBackupsBackupIdRoute
  '/_dashboard/deploy/$slug': typeof DashboardDeploySlugRoute
  '/_dashboard/deployments/$deploymentId': typeof DashboardDeploymentsDeploymentIdRoute
  '/_dashboard/jobs/$jobId': typeof DashboardJobsJobIdRouteWithChildren
  '/_dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/_dashboard/organizations/$organizationId': typeof DashboardOrganizationsOrganizationIdRoute
  '/_dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRouteWithChildren
  '/_dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/_dashboard/servers/$serverId': typeof DashboardServersServerIdRoute
  '/_dashboard/servers/new': typeof DashboardServersNewRoute
  '/_dashboard/services/$serviceId': typeof DashboardServicesServiceIdRouteWithChildren
  '/_dashboard/apps/': typeof DashboardAppsIndexRoute
  '/_dashboard/backups/': typeof DashboardBackupsIndexRoute
  '/_dashboard/deploy/': typeof DashboardDeployIndexRoute
  '/_dashboard/deployments/': typeof DashboardDeploymentsIndexRoute
  '/_dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/_dashboard/organizations/': typeof DashboardOrganizationsIndexRoute
  '/_dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/_dashboard/servers/': typeof DashboardServersIndexRoute
  '/_dashboard/apps/new/$appId': typeof DashboardAppsNewAppIdRoute
  '/_dashboard/jobs/$jobId/edit': typeof DashboardJobsJobIdEditRoute
  '/_dashboard/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/_dashboard/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/_dashboard/projects/$projectId/domains': typeof DashboardProjectsProjectIdDomainsRoute
  '/_dashboard/projects/$projectId/new': typeof DashboardProjectsProjectIdNewRoute
  '/_dashboard/projects/$projectId/scheduled-tasks': typeof DashboardProjectsProjectIdScheduledTasksRoute
  '/_dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/_dashboard/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/_dashboard/services/$serviceId/danger': typeof DashboardServicesServiceIdDangerRoute
  '/_dashboard/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/_dashboard/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/_dashboard/services/$serviceId/log-drains': typeof DashboardServicesServiceIdLogDrainsRoute
  '/_dashboard/services/$serviceId/metrics': typeof DashboardServicesServiceIdMetricsRoute
  '/_dashboard/services/$serviceId/previews': typeof DashboardServicesServiceIdPreviewsRoute
  '/_dashboard/services/$serviceId/route-rules': typeof DashboardServicesServiceIdRouteRulesRoute
  '/_dashboard/services/$serviceId/scheduled-tasks': typeof DashboardServicesServiceIdScheduledTasksRoute
  '/_dashboard/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/_dashboard/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/_dashboard/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/_dashboard/services/$serviceId/volumes': typeof DashboardServicesServiceIdVolumesRoute
  '/_dashboard/services/$serviceId/webhooks': typeof DashboardServicesServiceIdWebhooksRoute
  '/_dashboard/apps/new/': typeof DashboardAppsNewIndexRoute
  '/_dashboard/jobs/$jobId/': typeof DashboardJobsJobIdIndexRoute
  '/_dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/_dashboard/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/apps'
    | '/audit'
    | '/backups'
    | '/billing'
    | '/deploy'
    | '/deployments'
    | '/dns'
    | '/domains'
    | '/jobs'
    | '/library'
    | '/monitoring'
    | '/organizations'
    | '/profile'
    | '/projects'
    | '/servers'
    | '/settings'
    | '/apps/new'
    | '/backups/$backupId'
    | '/deploy/$slug'
    | '/deployments/$deploymentId'
    | '/jobs/$jobId'
    | '/jobs/new'
    | '/organizations/$organizationId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/services/$serviceId'
    | '/apps/'
    | '/backups/'
    | '/deploy/'
    | '/deployments/'
    | '/jobs/'
    | '/organizations/'
    | '/projects/'
    | '/servers/'
    | '/apps/new/$appId'
    | '/jobs/$jobId/edit'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/new'
    | '/projects/$projectId/scheduled-tasks'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/danger'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/log-drains'
    | '/services/$serviceId/metrics'
    | '/services/$serviceId/previews'
    | '/services/$serviceId/route-rules'
    | '/services/$serviceId/scheduled-tasks'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/services/$serviceId/volumes'
    | '/services/$serviceId/webhooks'
    | '/apps/new/'
    | '/jobs/$jobId/'
    | '/projects/$projectId/'
    | '/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/verify-email'
    | '/audit'
    | '/billing'
    | '/dns'
    | '/domains'
    | '/library'
    | '/monitoring'
    | '/profile'
    | '/settings'
    | '/backups/$backupId'
    | '/deploy/$slug'
    | '/deployments/$deploymentId'
    | '/jobs/new'
    | '/organizations/$organizationId'
    | '/projects/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/apps'
    | '/backups'
    | '/deploy'
    | '/deployments'
    | '/jobs'
    | '/organizations'
    | '/projects'
    | '/servers'
    | '/apps/new/$appId'
    | '/jobs/$jobId/edit'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/domains'
    | '/projects/$projectId/new'
    | '/projects/$projectId/scheduled-tasks'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/danger'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/log-drains'
    | '/services/$serviceId/metrics'
    | '/services/$serviceId/previews'
    | '/services/$serviceId/route-rules'
    | '/services/$serviceId/scheduled-tasks'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/services/$serviceId/volumes'
    | '/services/$serviceId/webhooks'
    | '/apps/new'
    | '/jobs/$jobId'
    | '/projects/$projectId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_auth/verify-email'
    | '/_dashboard/apps'
    | '/_dashboard/audit'
    | '/_dashboard/backups'
    | '/_dashboard/billing'
    | '/_dashboard/deploy'
    | '/_dashboard/deployments'
    | '/_dashboard/dns'
    | '/_dashboard/domains'
    | '/_dashboard/jobs'
    | '/_dashboard/library'
    | '/_dashboard/monitoring'
    | '/_dashboard/organizations'
    | '/_dashboard/profile'
    | '/_dashboard/projects'
    | '/_dashboard/servers'
    | '/_dashboard/settings'
    | '/_dashboard/'
    | '/_dashboard/apps/new'
    | '/_dashboard/backups/$backupId'
    | '/_dashboard/deploy/$slug'
    | '/_dashboard/deployments/$deploymentId'
    | '/_dashboard/jobs/$jobId'
    | '/_dashboard/jobs/new'
    | '/_dashboard/organizations/$organizationId'
    | '/_dashboard/projects/$projectId'
    | '/_dashboard/projects/new'
    | '/_dashboard/servers/$serverId'
    | '/_dashboard/servers/new'
    | '/_dashboard/services/$serviceId'
    | '/_dashboard/apps/'
    | '/_dashboard/backups/'
    | '/_dashboard/deploy/'
    | '/_dashboard/deployments/'
    | '/_dashboard/jobs/'
    | '/_dashboard/organizations/'
    | '/_dashboard/projects/'
    | '/_dashboard/servers/'
    | '/_dashboard/apps/new/$appId'
    | '/_dashboard/jobs/$jobId/edit'
    | '/_dashboard/projects/$projectId/canvas'
    | '/_dashboard/projects/$projectId/compose'
    | '/_dashboard/projects/$projectId/domains'
    | '/_dashboard/projects/$projectId/new'
    | '/_dashboard/projects/$projectId/scheduled-tasks'
    | '/_dashboard/projects/$projectId/settings'
    | '/_dashboard/services/$serviceId/build'
    | '/_dashboard/services/$serviceId/danger'
    | '/_dashboard/services/$serviceId/deployments'
    | '/_dashboard/services/$serviceId/domains'
    | '/_dashboard/services/$serviceId/log-drains'
    | '/_dashboard/services/$serviceId/metrics'
    | '/_dashboard/services/$serviceId/previews'
    | '/_dashboard/services/$serviceId/route-rules'
    | '/_dashboard/services/$serviceId/scheduled-tasks'
    | '/_dashboard/services/$serviceId/serverless'
    | '/_dashboard/services/$serviceId/terminal'
    | '/_dashboard/services/$serviceId/variables'
    | '/_dashboard/services/$serviceId/volumes'
    | '/_dashboard/services/$serviceId/webhooks'
    | '/_dashboard/apps/new/'
    | '/_dashboard/jobs/$jobId/'
    | '/_dashboard/projects/$projectId/'
    | '/_dashboard/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps': {
      id: '/_dashboard/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof DashboardAppsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit': {
      id: '/_dashboard/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/backups': {
      id: '/_dashboard/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof DashboardBackupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/billing': {
      id: '/_dashboard/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deploy': {
      id: '/_dashboard/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DashboardDeployRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deployments': {
      id: '/_dashboard/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dns': {
      id: '/_dashboard/dns'
      path: '/dns'
      fullPath: '/dns'
      preLoaderRoute: typeof DashboardDnsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/domains': {
      id: '/_dashboard/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/jobs': {
      id: '/_dashboard/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/library': {
      id: '/_dashboard/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/monitoring': {
      id: '/_dashboard/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof DashboardMonitoringRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/organizations': {
      id: '/_dashboard/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof DashboardOrganizationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/profile': {
      id: '/_dashboard/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/servers': {
      id: '/_dashboard/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof DashboardServersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps/': {
      id: '/_dashboard/apps/'
      path: '/'
      fullPath: '/apps/'
      preLoaderRoute: typeof DashboardAppsIndexRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/_dashboard/apps/new': {
      id: '/_dashboard/apps/new'
      path: '/new'
      fullPath: '/apps/new'
      preLoaderRoute: typeof DashboardAppsNewRouteImport
      parentRoute: typeof DashboardAppsRoute
    }
    '/_dashboard/backups/': {
      id: '/_dashboard/backups/'
      path: '/'
      fullPath: '/backups/'
      preLoaderRoute: typeof DashboardBackupsIndexRouteImport
      parentRoute: typeof DashboardBackupsRoute
    }
    '/_dashboard/backups/$backupId': {
      id: '/_dashboard/backups/$backupId'
      path: '/$backupId'
      fullPath: '/backups/$backupId'
      preLoaderRoute: typeof DashboardBackupsBackupIdRouteImport
      parentRoute: typeof DashboardBackupsRoute
    }
    '/_dashboard/deploy/': {
      id: '/_dashboard/deploy/'
      path: '/'
      fullPath: '/deploy/'
      preLoaderRoute: typeof DashboardDeployIndexRouteImport
      parentRoute: typeof DashboardDeployRoute
    }
    '/_dashboard/deploy/$slug': {
      id: '/_dashboard/deploy/$slug'
      path: '/$slug'
      fullPath: '/deploy/$slug'
      preLoaderRoute: typeof DashboardDeploySlugRouteImport
      parentRoute: typeof DashboardDeployRoute
    }
    '/_dashboard/deployments/': {
      id: '/_dashboard/deployments/'
      path: '/'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DashboardDeploymentsIndexRouteImport
      parentRoute: typeof DashboardDeploymentsRoute
    }
    '/_dashboard/deployments/$deploymentId': {
      id: '/_dashboard/deployments/$deploymentId'
      path: '/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DashboardDeploymentsDeploymentIdRouteImport
      parentRoute: typeof DashboardDeploymentsRoute
    }
    '/_dashboard/jobs/': {
      id: '/_dashboard/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardJobsRoute
    }
    '/_dashboard/jobs/$jobId': {
      id: '/_dashboard/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof DashboardJobsJobIdRouteImport
      parentRoute: typeof DashboardJobsRoute
    }
    '/_dashboard/jobs/new': {
      id: '/_dashboard/jobs/new'
      path: '/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof DashboardJobsNewRouteImport
      parentRoute: typeof DashboardJobsRoute
    }
    '/_dashboard/organizations/': {
      id: '/_dashboard/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof DashboardOrganizationsIndexRouteImport
      parentRoute: typeof DashboardOrganizationsRoute
    }
    '/_dashboard/organizations/$organizationId': {
      id: '/_dashboard/organizations/$organizationId'
      path: '/$organizationId'
      fullPath: '/organizations/$organizationId'
      preLoaderRoute: typeof DashboardOrganizationsOrganizationIdRouteImport
      parentRoute: typeof DashboardOrganizationsRoute
    }
    '/_dashboard/projects/': {
      id: '/_dashboard/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId': {
      id: '/_dashboard/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/new': {
      id: '/_dashboard/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/servers/': {
      id: '/_dashboard/servers/'
      path: '/'
      fullPath: '/servers/'
      preLoaderRoute: typeof DashboardServersIndexRouteImport
      parentRoute: typeof DashboardServersRoute
    }
    '/_dashboard/servers/$serverId': {
      id: '/_dashboard/servers/$serverId'
      path: '/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof DashboardServersServerIdRouteImport
      parentRoute: typeof DashboardServersRoute
    }
    '/_dashboard/servers/new': {
      id: '/_dashboard/servers/new'
      path: '/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof DashboardServersNewRouteImport
      parentRoute: typeof DashboardServersRoute
    }
    '/_dashboard/services/$serviceId': {
      id: '/_dashboard/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof DashboardServicesServiceIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/apps/new/': {
      id: '/_dashboard/apps/new/'
      path: '/'
      fullPath: '/apps/new/'
      preLoaderRoute: typeof DashboardAppsNewIndexRouteImport
      parentRoute: typeof DashboardAppsNewRoute
    }
    '/_dashboard/apps/new/$appId': {
      id: '/_dashboard/apps/new/$appId'
      path: '/$appId'
      fullPath: '/apps/new/$appId'
      preLoaderRoute: typeof DashboardAppsNewAppIdRouteImport
      parentRoute: typeof DashboardAppsNewRoute
    }
    '/_dashboard/jobs/$jobId/': {
      id: '/_dashboard/jobs/$jobId/'
      path: '/'
      fullPath: '/jobs/$jobId/'
      preLoaderRoute: typeof DashboardJobsJobIdIndexRouteImport
      parentRoute: typeof DashboardJobsJobIdRoute
    }
    '/_dashboard/jobs/$jobId/edit': {
      id: '/_dashboard/jobs/$jobId/edit'
      path: '/edit'
      fullPath: '/jobs/$jobId/edit'
      preLoaderRoute: typeof DashboardJobsJobIdEditRouteImport
      parentRoute: typeof DashboardJobsJobIdRoute
    }
    '/_dashboard/projects/$projectId/': {
      id: '/_dashboard/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/canvas': {
      id: '/_dashboard/projects/$projectId/canvas'
      path: '/canvas'
      fullPath: '/projects/$projectId/canvas'
      preLoaderRoute: typeof DashboardProjectsProjectIdCanvasRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/compose': {
      id: '/_dashboard/projects/$projectId/compose'
      path: '/compose'
      fullPath: '/projects/$projectId/compose'
      preLoaderRoute: typeof DashboardProjectsProjectIdComposeRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/domains': {
      id: '/_dashboard/projects/$projectId/domains'
      path: '/domains'
      fullPath: '/projects/$projectId/domains'
      preLoaderRoute: typeof DashboardProjectsProjectIdDomainsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/new': {
      id: '/_dashboard/projects/$projectId/new'
      path: '/new'
      fullPath: '/projects/$projectId/new'
      preLoaderRoute: typeof DashboardProjectsProjectIdNewRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/scheduled-tasks': {
      id: '/_dashboard/projects/$projectId/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/projects/$projectId/scheduled-tasks'
      preLoaderRoute: typeof DashboardProjectsProjectIdScheduledTasksRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/projects/$projectId/settings': {
      id: '/_dashboard/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdRoute
    }
    '/_dashboard/services/$serviceId/': {
      id: '/_dashboard/services/$serviceId/'
      path: '/'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof DashboardServicesServiceIdIndexRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/build': {
      id: '/_dashboard/services/$serviceId/build'
      path: '/build'
      fullPath: '/services/$serviceId/build'
      preLoaderRoute: typeof DashboardServicesServiceIdBuildRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/danger': {
      id: '/_dashboard/services/$serviceId/danger'
      path: '/danger'
      fullPath: '/services/$serviceId/danger'
      preLoaderRoute: typeof DashboardServicesServiceIdDangerRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/deployments': {
      id: '/_dashboard/services/$serviceId/deployments'
      path: '/deployments'
      fullPath: '/services/$serviceId/deployments'
      preLoaderRoute: typeof DashboardServicesServiceIdDeploymentsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/domains': {
      id: '/_dashboard/services/$serviceId/domains'
      path: '/domains'
      fullPath: '/services/$serviceId/domains'
      preLoaderRoute: typeof DashboardServicesServiceIdDomainsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/log-drains': {
      id: '/_dashboard/services/$serviceId/log-drains'
      path: '/log-drains'
      fullPath: '/services/$serviceId/log-drains'
      preLoaderRoute: typeof DashboardServicesServiceIdLogDrainsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/metrics': {
      id: '/_dashboard/services/$serviceId/metrics'
      path: '/metrics'
      fullPath: '/services/$serviceId/metrics'
      preLoaderRoute: typeof DashboardServicesServiceIdMetricsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/previews': {
      id: '/_dashboard/services/$serviceId/previews'
      path: '/previews'
      fullPath: '/services/$serviceId/previews'
      preLoaderRoute: typeof DashboardServicesServiceIdPreviewsRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/route-rules': {
      id: '/_dashboard/services/$serviceId/route-rules'
      path: '/route-rules'
      fullPath: '/services/$serviceId/route-rules'
      preLoaderRoute: typeof DashboardServicesServiceIdRouteRulesRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/scheduled-tasks': {
      id: '/_dashboard/services/$serviceId/scheduled-tasks'
      path: '/scheduled-tasks'
      fullPath: '/services/$serviceId/scheduled-tasks'
      preLoaderRoute: typeof DashboardServicesServiceIdScheduledTasksRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/serverless': {
      id: '/_dashboard/services/$serviceId/serverless'
      path: '/serverless'
      fullPath: '/services/$serviceId/serverless'
      preLoaderRoute: typeof DashboardServicesServiceIdServerlessRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/terminal': {
      id: '/_dashboard/services/$serviceId/terminal'
      path: '/terminal'
      fullPath: '/services/$serviceId/terminal'
      preLoaderRoute: typeof DashboardServicesServiceIdTerminalRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/variables': {
      id: '/_dashboard/services/$serviceId/variables'
      path: '/variables'
      fullPath: '/services/$serviceId/variables'
      preLoaderRoute: typeof DashboardServicesServiceIdVariablesRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/volumes': {
      id: '/_dashboard/services/$serviceId/volumes'
      path: '/volumes'
      fullPath: '/services/$serviceId/volumes'
      preLoaderRoute: typeof DashboardServicesServiceIdVolumesRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
    '/_dashboard/services/$serviceId/webhooks': {
      id: '/_dashboard/services/$serviceId/webhooks'
      path: '/webhooks'
      fullPath: '/services/$serviceId/webhooks'
      preLoaderRoute: typeof DashboardServicesServiceIdWebhooksRouteImport
      parentRoute: typeof DashboardServicesServiceIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardAppsNewRouteChildren {
  DashboardAppsNewAppIdRoute: typeof DashboardAppsNewAppIdRoute
  DashboardAppsNewIndexRoute: typeof DashboardAppsNewIndexRoute
}

const DashboardAppsNewRouteChildren: DashboardAppsNewRouteChildren = {
  DashboardAppsNewAppIdRoute: DashboardAppsNewAppIdRoute,
  DashboardAppsNewIndexRoute: DashboardAppsNewIndexRoute,
}

const DashboardAppsNewRouteWithChildren =
  DashboardAppsNewRoute._addFileChildren(DashboardAppsNewRouteChildren)

interface DashboardAppsRouteChildren {
  DashboardAppsNewRoute: typeof DashboardAppsNewRouteWithChildren
  DashboardAppsIndexRoute: typeof DashboardAppsIndexRoute
}

const DashboardAppsRouteChildren: DashboardAppsRouteChildren = {
  DashboardAppsNewRoute: DashboardAppsNewRouteWithChildren,
  DashboardAppsIndexRoute: DashboardAppsIndexRoute,
}

const DashboardAppsRouteWithChildren = DashboardAppsRoute._addFileChildren(
  DashboardAppsRouteChildren,
)

interface DashboardBackupsRouteChildren {
  DashboardBackupsBackupIdRoute: typeof DashboardBackupsBackupIdRoute
  DashboardBackupsIndexRoute: typeof DashboardBackupsIndexRoute
}

const DashboardBackupsRouteChildren: DashboardBackupsRouteChildren = {
  DashboardBackupsBackupIdRoute: DashboardBackupsBackupIdRoute,
  DashboardBackupsIndexRoute: DashboardBackupsIndexRoute,
}

const DashboardBackupsRouteWithChildren =
  DashboardBackupsRoute._addFileChildren(DashboardBackupsRouteChildren)

interface DashboardDeployRouteChildren {
  DashboardDeploySlugRoute: typeof DashboardDeploySlugRoute
  DashboardDeployIndexRoute: typeof DashboardDeployIndexRoute
}

const DashboardDeployRouteChildren: DashboardDeployRouteChildren = {
  DashboardDeploySlugRoute: DashboardDeploySlugRoute,
  DashboardDeployIndexRoute: DashboardDeployIndexRoute,
}

const DashboardDeployRouteWithChildren = DashboardDeployRoute._addFileChildren(
  DashboardDeployRouteChildren,
)

interface DashboardDeploymentsRouteChildren {
  DashboardDeploymentsDeploymentIdRoute: typeof DashboardDeploymentsDeploymentIdRoute
  DashboardDeploymentsIndexRoute: typeof DashboardDeploymentsIndexRoute
}

const DashboardDeploymentsRouteChildren: DashboardDeploymentsRouteChildren = {
  DashboardDeploymentsDeploymentIdRoute: DashboardDeploymentsDeploymentIdRoute,
  DashboardDeploymentsIndexRoute: DashboardDeploymentsIndexRoute,
}

const DashboardDeploymentsRouteWithChildren =
  DashboardDeploymentsRoute._addFileChildren(DashboardDeploymentsRouteChildren)

interface DashboardJobsJobIdRouteChildren {
  DashboardJobsJobIdEditRoute: typeof DashboardJobsJobIdEditRoute
  DashboardJobsJobIdIndexRoute: typeof DashboardJobsJobIdIndexRoute
}

const DashboardJobsJobIdRouteChildren: DashboardJobsJobIdRouteChildren = {
  DashboardJobsJobIdEditRoute: DashboardJobsJobIdEditRoute,
  DashboardJobsJobIdIndexRoute: DashboardJobsJobIdIndexRoute,
}

const DashboardJobsJobIdRouteWithChildren =
  DashboardJobsJobIdRoute._addFileChildren(DashboardJobsJobIdRouteChildren)

interface DashboardJobsRouteChildren {
  DashboardJobsJobIdRoute: typeof DashboardJobsJobIdRouteWithChildren
  DashboardJobsNewRoute: typeof DashboardJobsNewRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
}

const DashboardJobsRouteChildren: DashboardJobsRouteChildren = {
  DashboardJobsJobIdRoute: DashboardJobsJobIdRouteWithChildren,
  DashboardJobsNewRoute: DashboardJobsNewRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
}

const DashboardJobsRouteWithChildren = DashboardJobsRoute._addFileChildren(
  DashboardJobsRouteChildren,
)

interface DashboardOrganizationsRouteChildren {
  DashboardOrganizationsOrganizationIdRoute: typeof DashboardOrganizationsOrganizationIdRoute
  DashboardOrganizationsIndexRoute: typeof DashboardOrganizationsIndexRoute
}

const DashboardOrganizationsRouteChildren: DashboardOrganizationsRouteChildren =
  {
    DashboardOrganizationsOrganizationIdRoute:
      DashboardOrganizationsOrganizationIdRoute,
    DashboardOrganizationsIndexRoute: DashboardOrganizationsIndexRoute,
  }

const DashboardOrganizationsRouteWithChildren =
  DashboardOrganizationsRoute._addFileChildren(
    DashboardOrganizationsRouteChildren,
  )

interface DashboardProjectsProjectIdRouteChildren {
  DashboardProjectsProjectIdCanvasRoute: typeof DashboardProjectsProjectIdCanvasRoute
  DashboardProjectsProjectIdComposeRoute: typeof DashboardProjectsProjectIdComposeRoute
  DashboardProjectsProjectIdDomainsRoute: typeof DashboardProjectsProjectIdDomainsRoute
  DashboardProjectsProjectIdNewRoute: typeof DashboardProjectsProjectIdNewRoute
  DashboardProjectsProjectIdScheduledTasksRoute: typeof DashboardProjectsProjectIdScheduledTasksRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsProjectIdRouteChildren: DashboardProjectsProjectIdRouteChildren =
  {
    DashboardProjectsProjectIdCanvasRoute:
      DashboardProjectsProjectIdCanvasRoute,
    DashboardProjectsProjectIdComposeRoute:
      DashboardProjectsProjectIdComposeRoute,
    DashboardProjectsProjectIdDomainsRoute:
      DashboardProjectsProjectIdDomainsRoute,
    DashboardProjectsProjectIdNewRoute: DashboardProjectsProjectIdNewRoute,
    DashboardProjectsProjectIdScheduledTasksRoute:
      DashboardProjectsProjectIdScheduledTasksRoute,
    DashboardProjectsProjectIdSettingsRoute:
      DashboardProjectsProjectIdSettingsRoute,
    DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
  }

const DashboardProjectsProjectIdRouteWithChildren =
  DashboardProjectsProjectIdRoute._addFileChildren(
    DashboardProjectsProjectIdRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRouteWithChildren
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRouteWithChildren,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardServersRouteChildren {
  DashboardServersServerIdRoute: typeof DashboardServersServerIdRoute
  DashboardServersNewRoute: typeof DashboardServersNewRoute
  DashboardServersIndexRoute: typeof DashboardServersIndexRoute
}

const DashboardServersRouteChildren: DashboardServersRouteChildren = {
  DashboardServersServerIdRoute: DashboardServersServerIdRoute,
  DashboardServersNewRoute: DashboardServersNewRoute,
  DashboardServersIndexRoute: DashboardServersIndexRoute,
}

const DashboardServersRouteWithChildren =
  DashboardServersRoute._addFileChildren(DashboardServersRouteChildren)

interface DashboardServicesServiceIdRouteChildren {
  DashboardServicesServiceIdBuildRoute: typeof DashboardServicesServiceIdBuildRoute
  DashboardServicesServiceIdDangerRoute: typeof DashboardServicesServiceIdDangerRoute
  DashboardServicesServiceIdDeploymentsRoute: typeof DashboardServicesServiceIdDeploymentsRoute
  DashboardServicesServiceIdDomainsRoute: typeof DashboardServicesServiceIdDomainsRoute
  DashboardServicesServiceIdLogDrainsRoute: typeof DashboardServicesServiceIdLogDrainsRoute
  DashboardServicesServiceIdMetricsRoute: typeof DashboardServicesServiceIdMetricsRoute
  DashboardServicesServiceIdPreviewsRoute: typeof DashboardServicesServiceIdPreviewsRoute
  DashboardServicesServiceIdRouteRulesRoute: typeof DashboardServicesServiceIdRouteRulesRoute
  DashboardServicesServiceIdScheduledTasksRoute: typeof DashboardServicesServiceIdScheduledTasksRoute
  DashboardServicesServiceIdServerlessRoute: typeof DashboardServicesServiceIdServerlessRoute
  DashboardServicesServiceIdTerminalRoute: typeof DashboardServicesServiceIdTerminalRoute
  DashboardServicesServiceIdVariablesRoute: typeof DashboardServicesServiceIdVariablesRoute
  DashboardServicesServiceIdVolumesRoute: typeof DashboardServicesServiceIdVolumesRoute
  DashboardServicesServiceIdWebhooksRoute: typeof DashboardServicesServiceIdWebhooksRoute
  DashboardServicesServiceIdIndexRoute: typeof DashboardServicesServiceIdIndexRoute
}

const DashboardServicesServiceIdRouteChildren: DashboardServicesServiceIdRouteChildren =
  {
    DashboardServicesServiceIdBuildRoute: DashboardServicesServiceIdBuildRoute,
    DashboardServicesServiceIdDangerRoute:
      DashboardServicesServiceIdDangerRoute,
    DashboardServicesServiceIdDeploymentsRoute:
      DashboardServicesServiceIdDeploymentsRoute,
    DashboardServicesServiceIdDomainsRoute:
      DashboardServicesServiceIdDomainsRoute,
    DashboardServicesServiceIdLogDrainsRoute:
      DashboardServicesServiceIdLogDrainsRoute,
    DashboardServicesServiceIdMetricsRoute:
      DashboardServicesServiceIdMetricsRoute,
    DashboardServicesServiceIdPreviewsRoute:
      DashboardServicesServiceIdPreviewsRoute,
    DashboardServicesServiceIdRouteRulesRoute:
      DashboardServicesServiceIdRouteRulesRoute,
    DashboardServicesServiceIdScheduledTasksRoute:
      DashboardServicesServiceIdScheduledTasksRoute,
    DashboardServicesServiceIdServerlessRoute:
      DashboardServicesServiceIdServerlessRoute,
    DashboardServicesServiceIdTerminalRoute:
      DashboardServicesServiceIdTerminalRoute,
    DashboardServicesServiceIdVariablesRoute:
      DashboardServicesServiceIdVariablesRoute,
    DashboardServicesServiceIdVolumesRoute:
      DashboardServicesServiceIdVolumesRoute,
    DashboardServicesServiceIdWebhooksRoute:
      DashboardServicesServiceIdWebhooksRoute,
    DashboardServicesServiceIdIndexRoute: DashboardServicesServiceIdIndexRoute,
  }

const DashboardServicesServiceIdRouteWithChildren =
  DashboardServicesServiceIdRoute._addFileChildren(
    DashboardServicesServiceIdRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardAppsRoute: typeof DashboardAppsRouteWithChildren
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardBackupsRoute: typeof DashboardBackupsRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardDeployRoute: typeof DashboardDeployRouteWithChildren
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRouteWithChildren
  DashboardDnsRoute: typeof DashboardDnsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardJobsRoute: typeof DashboardJobsRouteWithChildren
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardMonitoringRoute: typeof DashboardMonitoringRoute
  DashboardOrganizationsRoute: typeof DashboardOrganizationsRouteWithChildren
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardServersRoute: typeof DashboardServersRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardServicesServiceIdRoute: typeof DashboardServicesServiceIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAppsRoute: DashboardAppsRouteWithChildren,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardBackupsRoute: DashboardBackupsRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardDeployRoute: DashboardDeployRouteWithChildren,
  DashboardDeploymentsRoute: DashboardDeploymentsRouteWithChildren,
  DashboardDnsRoute: DashboardDnsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardJobsRoute: DashboardJobsRouteWithChildren,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardMonitoringRoute: DashboardMonitoringRoute,
  DashboardOrganizationsRoute: DashboardOrganizationsRouteWithChildren,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardServersRoute: DashboardServersRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardServicesServiceIdRoute: DashboardServicesServiceIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
