x-codedock:
  is_one_click: true
  name: NocoDB
  description: Open-source Airtable alternative
  category: database-tools
  icon: nocodb
  secrets:
    - var: NC_AUTH_JWT_SECRET
      label: Auth JWT secret
      length: 32
services:
  nocodb:
    image: nocodb/nocodb
    restart: always
    ports:
      - "8080"
    environment:
      - NC_AUTH_JWT_SECRET=${secret:NC_AUTH_JWT_SECRET}
    volumes:
      - nocodb-data:/usr/app/data
volumes:
  nocodb-data:
