x-codedock:
  is_one_click: true
  name: Supabase Studio
  description: Open-source Firebase alternative
  category: developer-tools
  icon: supabase-studio
services:
  studio:
    image: supabase/studio
    restart: always
    ports:
      - "3000"
  kong:
    image: kong:latest
    restart: always
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=supabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d supabase"]
      interval: 10s
      timeout: 5s
      retries: 5
